### PR TITLE
fixes issue #98

### PR DESCRIPTION
**Pull request by dkulczak**
Hello Kate,

Hopefully this fixes it.

Deb

### CODE REVIEW

**Comment by kateefly** [comment]
Just realized that I hadn't put this in the PR! My comments from issue#98:

Could you add a permalink? Something like

`permalink: contributors`

Right below `title: contributors` in the front matter.

**Comment by dkulczak** [comment]
Yes, will try to take care of this evening.  Also, it looks like there's at least one update request to the 2019 list, which I will also do.

**Comment by kateefly** [comment]
Sounds good. Thanks @dkulczak!

**Comment by kateefly** [comment]
Duplicate pull request already approved (see PR125)

**Pull request closed without merging**
