### PR TITLE
Relative links in previous update were relative to main site and not …

### PR DESCRIPTION
**Pull request by kateefly**
…Sandbox. So they don't work as intended as they currently are (though they're right for the production/main site).

Before transferring the production site these links will need to be updated.

### CODE REVIEW

**Comment by kateefly** [comment]
@kgrons Could you review and approve?

**Comment by kateefly** [comment]
@plampron2 Could you review?

**Comment by plampron2** [comment]
as far as I can tell it looks good!

**Comment by plampron2** [comment]
There is one other spot in the collaborations page that has a link to /Framework - does that also need to be changed (I don't think that one has been updated with a perma-link yet either)?

**Comment by kateefly** [comment]
I think that's ok for now. We can make a note of it as a thing to fix in the next week or so. Thanks @plampron2 !

**Pull request merged**
