### PR TITLE
Issue#281

### PR DESCRIPTION
**Pull request by kateefly**
Covers both issue#281 and #284 .

### CODE REVIEW

**Comment by akhtars** [comment]
Yes, I can review by the end of the day, thanks. Sorry for the delay.

**Comment by kateefly** [comment]
I should have been more clear about the time sensitivity! Thank you @akhtars and please let me know if you need anything from me

**Comment by akhtars** [comment]
The changes look good and can be merged. Thought I'd check with @kateefly about two minor things I observed reviewing the Contributors page, neither of which were introduced by this edit:

- Under "Leadership", should "who lead working during 2022" be changed to "who led working during 2022", or is it intended to be present tense?
- Are "Ryan Mendenhall (2017)" and "Timothy Ryan Mendenhall (2016)" the same individual?

Happy to merge these commits as-is and if either of the above warrants further changes I can open another issue?

**Comment by kateefly** [comment]
Thanks for the catch on the present tense issue! I've fixed it and it should read better now.

As for whether or not that is the same person, I honestly have no idea! We gave people space for feedback and no one spoke up to confirm that or not. Since it's been a while, I think it's ok to leave them as is for now.

**Comment by akhtars** [comment]
Thanks!

**Pull request merged**
