### PR TITLE
Making sure layouts and page titles are consistent

### PR DESCRIPTION
**Pull request by kateefly**
@plampron2 would you review?

### CODE REVIEW

**Comment by plampron2** [comment]
There is some inconsistency in capitalization of both titles and permalinks (ex: the skillbuilding title is capitalized but the permalink is not, but the projects permalink is capitalized and the title is not), but this is causing any problems with functionality of the website. @kateefly let me know if you want to fix them, if not I'll merge.

**Comment by kateefly** [comment]
They should be consistent now - would you review again @plampron2 ?

**Comment by plampron2** [comment]
I noticed the collaborations page title and permalink are both still lowercase and  the environmental scan page title is lowercase.

**Comment by kateefly** [comment]
Collaborations page should be ok now

**Pull request merged**
