### PR TITLE
fixes issue #96

### PR DESCRIPTION
**Pull request by plampron2**
fixed a typo, fixed front matter

### CODE REVIEW

**Comment by eightBitter** [comment]
The change in question looks good to me. I noticed in the files changed that some .sass-cache and _site files were changed. Since both of those files/directories are in the .gitignore file, should these changes be tracked in the git history?

**Comment by kateefly** [comment]
I think it'll be ok if .sass-cache and _site are included in the merge but I'll do a bit more research to make sure of this.

**Comment by kateefly** [comment]
After some research, I think I'd recommend using the `git rm --cached _site` and `git rm --cached .sass-cache` commands. This will remove the files and prevent any issues. To do this @plampron2, you'd just need to run those two commands and then push the changes to this same branch (and it'll show up in the pull request). Let me know if you need any help.

You can also see [https://stackoverflow.com/questions/47239763/why-do-site-files-still-sometimes-show-for-commiting](https://stackoverflow.com/questions/47239763/why-do-site-files-still-sometimes-show-for-commiting) for more info on this issue.

**Comment by plampron2** [comment]
I tried to run git rm --cached _site and got this error:
fatal: not removing '_site' recursively without -r

Any ideas?
I probably should only have added the one file that I changed but I wasn't really sure what the best practice for that was.

**Comment by kateefly** [comment]
Try `git rm -r --cached _site` (this will allow it to work recursively). If that doesn't work, try `git rm -r -f --cached _site` (this will force it to remove that folder and work recursively).

**Comment by plampron2** [comment]
Those seemed to work, however I tried to push it back out but nothing happened?

**Comment by kateefly** [comment]
You pushed your changes to the issue#96 branch, correct? I'm not sure why it wouldn't register but try once again and if it doesn't work, I'll approve the changes even with the other files. I don't think it'll cause an issue and the removing files was more trying to be very cautious. But if it's this much trouble, then the cautious approach probably isn't worth it.

**Pull request merged**
