### PR TITLE
Issue#8

### PR DESCRIPTION
**Pull request by billmcmillin**
Before merging, we'll need to decide on a direction for this issue.

It turns out our markdown was not being parsed by Jekyll because it was in html files. Kramdown allows the mixing of md and html, but only in md files and with this option at the beginning of the document:
{::options parse_block_html="true" /}
This allows code blocks to be interpreted as html, but in kramdown a code block begins with at most 3 spaces. So to get the parser to recognize the html tags, I had to change the indentation of the html.

So it appears we have two options:
1. continue to create content in html, converting any md to html
2. convert the html files to markdown and remove indents - this will allow mixing md and html, but we'll have to keep an eye on the indentation

Thoughts? Shall we wait for the next meeting to see what the group wants to do?

For details, see https://about.gitlab.com/2016/07/19/markdown-kramdown-tips-and-tricks/#mix-html-with-markdown

### CODE REVIEW

**Comment by kateefly** [comment]
I vote that we discuss this at the web group meeting/next group meeting.

**Comment by cmh2166** [comment]
@billmcmillin @kateefly @f8f8ff @jlhardes @scottythered please review and approve / ask questions by Monday July 17th.

**Comment by f8f8ff** [comment]
Q: Why am I seeing the tag `{::options parse_block_html="true" /}` in plain text in my .md file? A: First, the  pull request needs to be merged. If you're still having the issue, check that the tag is indented 3 spaces.

**Comment by kateefly** [comment]
I tried reviewing this PR and I think the Gemfile update is missing some of the gems we need. Here's what I got when I tried to do `bundle exec jekyll serve`

`Kate Flynn@LibrarySystems MINGW64 ~/desktop/Sandbox (issue#8)
$ bundle exec jekyll serve
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find i18n-0.8.4 in any of the sources (Bundler::GemNotFound)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/spec_set.rb:81:in `map!'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/spec_set.rb:81:in `materialize'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/definition.rb:159:in `specs'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/definition.rb:218:in `specs_for'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/definition.rb:207:in `requested_specs'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:109:in `block in definition_method'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:21:in `setup'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler.rb:101:in `setup'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.15.1/lib/bundler/setup.rb:20:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'`

**Comment by billmcmillin** [comment]
After seeing the mess made by modifying Gemfile.lock, I reverted it to what we had. Now Gemfile.lock should not appear in the 'files changed'. This issue should be resolved by branch issue#25.

**Pull request merged**
