### PR TITLE
add Jekyll intro and resources

### PR DESCRIPTION
**Pull request by kgrons**
contribution (resources, language) from Andrea L. via feedback document

### CODE REVIEW

**Comment by kateefly** [comment]
@kgrons , since the rest of the pages have front matter, this page needs it as well to display properly. You will need to specify the layout and title of the page in the front matter and you can see an example on the about page: https://raw.githubusercontent.com/DLFMetadataAssessment/Sandbox/master/about.markdown

Let me know if you have questions and thank you for doing this!

**Comment by kateefly** [comment]
@kgrons This page just needs front matter added to it before it can be merged into the site. Would you be able to do this?

This would be something like (taken from the about page):
```
---
layout: default
title: About
permalink: about
---
```

**Comment by kgrons** [comment]
@kateefly added new commit with front matter as you recommended. Thank you!

**Comment by kateefly** [comment]
One last small correction (sorry for not catching this earlier!). There needs to be a space between the header and the tables on lines 49-50 and 57-58. Otherwise, the tables won't display correctly.

**Pull request merged**
