### PR TITLE
Updated Framework page. Added permalink, bread crumbs and anchor tags…

### PR DESCRIPTION
**Pull request by kateefly**
…, also fixed bullets

### CODE REVIEW

**Comment by kateefly** [comment]
@akhtars would you take a look?

**Comment by akhtars** [comment]
This looks good to me, thanks. Two minor questions – under the "Supporting tool use" subsection, there's a link to the DLF Metadata Support Group page, and then also a footnote (numbered 2?) linking out there. Are both necessary? Also, the URL we give, `https://www.diglib.org/dlf-metadata-support-group/` now redirects to `https://www.diglib.org/groups/dlf-metadata-support-group/`. Would it be worth updating our link?

**Comment by kateefly** [comment]
Thanks @akhtars for the review - I think those changes sounds good. I've updated the references to the Metadata Support group.

**Comment by akhtars** [comment]
Thanks @kateefly, the only remaining thing I notice is it looks like there's a trailing `</a>` tag on line 125. I can remove if it it's easier that way; either way this is ready to merge after that.

**Comment by kateefly** [comment]
Please go ahead and do so! I'm in a meeting for the next hour and won't be able to get to it for a little bit.

**Pull request merged**
